baseurl = "http://localhost:1313/"
canonifyurls = true
languageCode = "en-us"
metadataformat = "yaml"
pygmentscodefences = true
pygmentsuseclasses = true
theme = "hyde"
title = "Diti [dot] me"

[[menu.main]]
	name   = "Posts"
	url    = "/post/"
	weight = 10
#[[menu.main]]
#	name   = "Projects"
#	url    = "proj/"
#	weight = 20
#[[menu.main]]
#	name   = "Characters"
#	url    = "char/"
#	weight = 30

[params]
copyright = "2016 Â© Dimitri â€œDitiâ€ Torterat â€“ Creative Commons BY SA"
description = " "
disqusShortname = "Diti"

[permalinks]
    post = "/post/:title/"
    page = "/:title/"

# Dimitri â€œDitiâ€ Torterat â€“ Creative Commons [BY SA ğŸ‡«ğŸ‡·](https://creativecommons.org/licenses/by-sa/3.0/fr/)

[blackfriday]
	smartypants	= false
	fractions = false
	smartDashes = false
	plainIDAnchors = true
