baseUrl: "https://diti.me/"
title: "Diti [dot] me"
theme: "dititash"

params:
  ghrepo: "https://github.com/Diti/diti.me"

enableGitInfo: true

sectionPagesMenu: "main"
menu:
  main:
    - name: "Posts"
      identifier: "post"
      url: "/post/"
      weight: 10
#    - name: "Projects"
#      url: "./proj/"
#      weight: 20
#    - name: "Characters"
#      identifier: "character"
#      url: "/char/"
#      weight: 30

copyright: "{year} Â© Dimitri â€œDitiâ€ Torterat"

# i18n
EnableMissingTranslationPlaceholders: true
languages:
  en:
    languageCode: "en"
    languageName: "ğŸ‡¬ğŸ‡§ English"
  fr:
    languageCode: "fr"
    languageName: "ğŸ‡«ğŸ‡· FranÃ§ais"

permalinks:
  char: "/char/:title/"
  post: "/post/:title/"
  page: "/:title/"

taxonomies:
  tag: "tags"
  category: "categories"

# Cosmetic & internal settings
enableGitInfo: true

blackfriday:
  smartypants: false
  fractions: false
  smartDashes: false
  plainIDAnchors: true
canonifyUrls: true
footnoteAnchorPrefix: "note-"
footnoteReturnLinkContents: "â†©"
metadataFormat: "yaml"
pygmentscodefences: true
pygmentsuseclasses: true

outputs:
  home: [ "HTML", "RSS" ]
  page: [ "HTML" ]
